onboarding = false

[theme]
name = "catppuccin" # tokyo-night, kanagawa, nord, rose-pine, gruvbox
custom.panel_bg = "reset" # transpaernt tab margin

[ui]
agent_panel_sort = "spaces"
show_agent_labels_on_pane_borders = true
sidebar_collapsed_mode = "hidden" # hide sidebar completely when it is collapsed
hide_tab_bar_when_single_tab = true # hide top bar when only one tab exists
prompt_new_tab_name = false # tmux-like behavior: create tab without prompt for naming

toast.delivery = "herdr"
sound.enabled = true

[experimental]
kitty_graphics = true
pane_history = true # https://zenn.dev/7shi/scraps/98218b6bc12734#%E2%91%A0-%E7%94%BB%E9%9D%A2%E5%B1%A5%E6%AD%B4%E3%81%AE%E5%BE%A9%E5%85%83-(pane_history)

[keys]
prefix = "ctrl+j"

focus_pane_left = ["super+h"]
focus_pane_down = ["super+j"]
focus_pane_up = ["super+k"]
focus_pane_right = ["super+l"]

cycle_pane_next = ["prefix+tab", "ctrl+tab"] # prefix+tab is the default keybind
cycle_pane_previous = ["prefix+shift+tab", "ctrl+shift+tab"]

copy_mode = ["prefix+[", "prefix+e"] # prefix+[ is the default keybind
edit_scrollback = "prefix+shift+e" # opens scrollback via $EDITOR

split_vertical = ["prefix+v", "prefix+%"]
split_horizontal = ["prefix+minus", "prefix+double_quote"]

previous_workspace = "prefix+("
next_workspace = "prefix+)"

previous_agent = "prefix+{"
next_agent = "prefix+}"

# tmux default: prefix+! detaches the pane into a new tab (break-pane)
[[keys.command]]
key = "prefix+!"
description = "break-pane"
type = "shell"
command = '"$HERDR_BIN_PATH" pane move "$HERDR_ACTIVE_PANE_ID" --new-tab --focus'
