# Variables {{{

# XDG Base Directories (NEED TO LOAD FIRST!!!!)
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_STATE_HOME="$HOME/.local/state"

# Environment variables
export LANG=en_US.UTF-8
export LANGUAGE=en_US.UTF-8
export LC_COLLATE=C # sort ASCII order rather than alphabetical one

export EDITOR=nvim
export SUDO_EDITOR=vim
export VISUAL=nvim
export MANPAGER=nvim +Man!

# Path
export PATH="$HOME/.local/bin:$PATH"
export PATH="$HOME/kjuq/bin:$PATH"

# Kjuq created
if [ -n "$TERMUX_VERSION" ]; then
	export KJUQ_DOCS="$HOME/storage/shared/kjuq/docs"
else
	export KJUQ_DOCS="$HOME/kjuq/docs"
fi

# Password-store
export PASSWORD_STORE_DIR="$HOME/kjuq/password-store"

# ghq
export GHQ_ROOT="$HOME/kjuq/ghq"

# Homebrew
export HOMEBREW_NO_ANALYTICS=1
export HOMEBREW_NO_ENV_HINTS=1

# # Bash
# mkdir --parents "$XDG_STATE_HOME/bash"
# export HISTFILE="$XDG_STATE_HOME/bash/history"

# Docker
export DOCKER_CONFIG="$XDG_CONFIG_HOME/docker"

# Python
export PYTHONSTARTUP="$XDG_CONFIG_HOME/python/pythonrc.py"
export PYTHON_HISTORY="$XDG_STATE_HOME/python/history" # not working so wrote `pythonrc.py` as a workaround
export PYTHONPYCACHEPREFIX="$XDG_CACHE_HOME/python" # no `__pycache__`
export PYTHONUSERBASE="$XDG_DATA_HOME/python" # base dir where packages will be installed via `pip install --user`

# Go
export GOPATH="$XDG_DATA_HOME/go"

# npm
export NPM_CONFIG_USERCONFIG="$XDG_CONFIG_HOME/npm/npmrc"

# Claude code
export CLAUDE_CONFIG_DIR="$XDG_CONFIG_HOME/claude"

# Cargo
export CARGO_HOME="$XDG_DATA_HOME"/cargo

# w3m
export W3M_DIR="$XDG_CONFIG_HOME/w3m"

# rclone
export RCLONE_EXCLUDE="*.DS_Store"

# fzf
set fzf_fd_opts "--hidden --exclude .git"
export FZF_DEFAULT_COMMAND="fd --type f $fzf_fd_opts"
export FZF_DEFAULT_OPTS='--height 40% --layout=reverse --border'

# ripgrep
export RIPGREP_CONFIG_PATH="$XDG_CONFIG_HOME/ripgrep/ripgreprc"

# NuGet
export NUGET_PACKAGES="$XDG_CACHE_HOME/NuGetPackages"

# PostgreSQL
export PSQL_HISTORY="$XDG_DATA_HOME/psql_history"

# Dotnet
export DOTNET_CLI_HOME="$XDG_DATA_HOME"/dotnet

# CUDA
export CUDA_CACHE_PATH="$XDG_CACHE_HOME"/nv

# urxvt
export RXVT_SOCKET="$XDG_RUNTIME_DIR"/urxvtd

# wgetrc
export WGETRC="$XDG_CONFIG_HOME/wget/wgetrc"

# cpanm
export PERL_CPANM_HOME="$XDG_CACHE_HOME/cpanm"

# irb
export IRBRC="$XDG_CONFIG_HOME"/irb/irbrc

# Ruby bundler
export BUNDLE_USER_CONFIG="$XDG_CONFIG_HOME"/bundle
export BUNDLE_USER_CACHE="$XDG_CACHE_HOME"/bundle
export BUNDLE_USER_PLUGIN="$XDG_DATA_HOME"/bundle

# Rustup
export RUSTUP_HOME="$XDG_DATA_HOME"/rustup

# Android
export ANDROID_USER_HOME="$XDG_DATA_HOME"/android

# OpenJDK (some applications don't respect this setting)
export _JAVA_OPTIONS="-Djava.util.prefs.userRoot=$XDG_CONFIG_HOME/java"

# GnuPG
export GNUPGHOME="$XDG_CONFIG_HOME/gnupg"
export GPG_TTY=(tty)

# Uncrustify
export UNCRUSTIFY_CONFIG="$XDG_CONFIG_HOME"/uncrustify/uncrustify.cfg

# nb
export NBRC_PATH="$XDG_CONFIG_HOME/nb/nbrc"
export NB_DIR="$XDG_DATA_HOME/nb"

# GUI toolkit
export GTK2_RC_FILES="$XDG_CONFIG_HOME/gtkrc-2.0/gtkrc"

# Defined at .profile generated by Manjaro
export QT_QPA_PLATFORMTHEME=qt5ct

# Xauthority
if [[ -v XDG_RUNTIME_DIR ]]; then
	export XAUTHORITY="$XDG_RUNTIME_DIR/Xauthority"
fi

# SSH-agent
if [[ -x "$(command -v ssh-agent)" ]]; then
	eval "$(ssh-agent -c)" >/dev/null
fi

# }}}

# vim: set foldmethod=marker :
