tap "kjuq/tap"
tap "homebrew/cask-fonts"

brew "bash"
brew "coreutils"
brew "curl"
brew "dust"
brew "eza"
brew "fd"
brew "fish"
brew "fzf"
brew "gh"
brew "git"
brew "less"
brew "mas"
brew "neovim"
brew "pass"
brew "pass-otp"
brew "pinentry-mac"
brew "python"
brew "ripgrep"
brew "tailscale", restart_service: true
brew "tmux"
brew "trash-cli"
brew "w3m"
brew "zoxide"

cask "betterdisplay"
cask "copyq"
cask "hammerspoon"
cask "linearmouse"
cask "qutebrowser"
cask "wezterm"

# homebrew/cask-fonts
cask "font-cozette"

# kjuq/tap
brew "osc52"
cask "font-pixel-m-plus"

# vim: set filetype=ruby :
