# AeroSpace Configuration

# # disable AeroSpace's original window splitting mechanism. I prefer i3-compatible style
# enable-normalization-flatten-containers = false
# enable-normalization-opposite-orientation-for-nested-containers = false

[gaps]

inner.horizontal = [{ monitor."^built-in retina display$"= 10 }, 20]
inner.vertical = [{ monitor."^built-in retina display$"= 8 }, 16]
outer.left = [{ monitor."^built-in retina display$"= 6 }, 40]
outer.bottom = [{ monitor."^built-in retina display$"= 6 }, 50]
outer.top = [{ monitor."^built-in retina display$"= 5 }, 35]
outer.right = [{ monitor."^built-in retina display$"= 6 }, 40]


[mode.main.binding]

cmd-tab = 'workspace-back-and-forth'
alt-tab = 'workspace-back-and-forth'

cmd-alt-ctrl-shift-m = 'exec-and-forget open -na Ghostty.app'

cmd-alt-ctrl-y = 'focus --boundaries-action wrap-around-the-workspace dfs-next'

cmd-alt-ctrl-h = 'focus --boundaries all-monitors-outer-frame --boundaries-action stop left'
cmd-alt-ctrl-j = 'focus --boundaries all-monitors-outer-frame --boundaries-action stop down'
cmd-alt-ctrl-k = 'focus --boundaries all-monitors-outer-frame --boundaries-action stop up'
cmd-alt-ctrl-l = 'focus --boundaries all-monitors-outer-frame --boundaries-action stop right'

# Moving across monitors is unconfortable for me
cmd-alt-ctrl-shift-h = 'move left'  # 'move --boundaries all-monitors-outer-frame left'
cmd-alt-ctrl-shift-j = 'move down'  # 'move --boundaries all-monitors-outer-frame down'
cmd-alt-ctrl-shift-k = 'move up'    # 'move --boundaries all-monitors-outer-frame up'
cmd-alt-ctrl-shift-l = 'move right' # 'move --boundaries all-monitors-outer-frame right'

cmd-alt-ctrl-shift-0 = 'join-with left'
cmd-alt-ctrl-shift-pageDown = 'join-with down'
cmd-alt-ctrl-shift-pageUp = 'join-with up'
cmd-alt-ctrl-shift-7 = 'join-with right'

cmd-alt-ctrl-n = ['flatten-workspace-tree', 'layout tiles horizontal', 'balance-sizes']

cmd-alt-ctrl-v = 'workspace 0'
cmd-alt-ctrl-d = 'workspace 1'
cmd-alt-ctrl-c = 'workspace 2'
cmd-alt-ctrl-x = 'workspace 3'
cmd-alt-ctrl-t = 'workspace 4'
cmd-alt-ctrl-s = 'workspace 5'
cmd-alt-ctrl-r = 'workspace 6'
cmd-alt-ctrl-p = 'workspace 7'
cmd-alt-ctrl-f = 'workspace 8'
cmd-alt-ctrl-w = 'workspace 9'

cmd-alt-ctrl-shift-v = 'move-node-to-workspace 0 --focus-follows-window'
cmd-alt-ctrl-shift-d = 'move-node-to-workspace 1 --focus-follows-window'
cmd-alt-ctrl-shift-c = 'move-node-to-workspace 2 --focus-follows-window'
cmd-alt-ctrl-shift-x = 'move-node-to-workspace 3 --focus-follows-window'
cmd-alt-ctrl-shift-t = 'move-node-to-workspace 4 --focus-follows-window'
cmd-alt-ctrl-shift-s = 'move-node-to-workspace 5 --focus-follows-window'
cmd-alt-ctrl-shift-r = 'move-node-to-workspace 6 --focus-follows-window'
cmd-alt-ctrl-shift-p = 'move-node-to-workspace 7 --focus-follows-window'
cmd-alt-ctrl-shift-f = 'move-node-to-workspace 8 --focus-follows-window'
cmd-alt-ctrl-shift-w = 'move-node-to-workspace 9 --focus-follows-window'
