# AeroSpace Configuration

# $mod = Mod4 (Command)
# $sac = Mod4 + Mod1 + Ctrl (Cmd + Alt + Ctrl)

[gaps]

inner.horizontal = 3
inner.vertical =   3
outer.left =       0
outer.bottom =     0
outer.top =        0
outer.right =      0

[mode.main.binding]
# Workspace back_and_forth
cmd-tab = 'workspace-back-and-forth'
alt-tab = 'workspace-back-and-forth'

# Change focus (i3: $sac+9 focus next)
cmd-alt-ctrl-9 = 'focus dfs-next --ignore-floating --boundaries-action wrap-around-the-workspace'

# Move focus (hjkl/directional)
cmd-alt-ctrl-0 = 'focus --boundaries all-monitors-outer-frame --boundaries-action stop left'
cmd-alt-ctrl-pageDown = 'focus --boundaries all-monitors-outer-frame --boundaries-action stop down'
cmd-alt-ctrl-pageUp = 'focus --boundaries all-monitors-outer-frame --boundaries-action stop up'
cmd-alt-ctrl-7 = 'focus --boundaries all-monitors-outer-frame --boundaries-action stop right'

# Move focused window
cmd-alt-ctrl-shift-0 = 'move --boundaries all-monitors-outer-frame left'
cmd-alt-ctrl-shift-pageDown = 'move --boundaries all-monitors-outer-frame down'
cmd-alt-ctrl-shift-pageUp = 'move --boundaries all-monitors-outer-frame up'
cmd-alt-ctrl-shift-7 = 'move --boundaries all-monitors-outer-frame right'

# --- Workspace Switch (sac + wskey) ---
cmd-alt-ctrl-backslash = 'workspace 0'
cmd-alt-ctrl-semicolon = 'workspace 1'
cmd-alt-ctrl-period = 'workspace 2'
cmd-alt-ctrl-comma = 'workspace 3'
cmd-alt-ctrl-rightSquareBracket = 'workspace 4' # bracketright
cmd-alt-ctrl-leftSquareBracket = 'workspace 5'  # bracketleft
cmd-alt-ctrl-slash = 'workspace 6'
cmd-alt-ctrl-backtick = 'workspace 7'      # grave
cmd-alt-ctrl-equal = 'workspace 8'
cmd-alt-ctrl-minus = 'workspace 9'

# --- Move to workspace with focused container (Shift + sac + wskey) ---
# AeroSpaceでは '--focus-follows-window' で「移動してそのワークスペースを追う」挙動になります
cmd-alt-ctrl-shift-backslash = 'move-node-to-workspace 0 --focus-follows-window'
cmd-alt-ctrl-shift-semicolon = 'move-node-to-workspace 1 --focus-follows-window'
cmd-alt-ctrl-shift-period = 'move-node-to-workspace 2 --focus-follows-window'
cmd-alt-ctrl-shift-comma = 'move-node-to-workspace 3 --focus-follows-window'
cmd-alt-ctrl-shift-rightSquareBracket = 'move-node-to-workspace 4 --focus-follows-window'
cmd-alt-ctrl-shift-leftSquareBracket = 'move-node-to-workspace 5 --focus-follows-window'
cmd-alt-ctrl-shift-slash = 'move-node-to-workspace 6 --focus-follows-window'
cmd-alt-ctrl-shift-backtick = 'move-node-to-workspace 7 --focus-follows-window'
cmd-alt-ctrl-shift-equal = 'move-node-to-workspace 8 --focus-follows-window'
cmd-alt-ctrl-shift-minus = 'move-node-to-workspace 9 --focus-follows-window'

### Scratchpad (https://github.com/cristianoliveira/aerospace-scratchpad)
# cmd-alt-ctrl-g = 'exec-and-forget aerospace-scratchpad move Alacritty'
# cmd-alt-ctrl-quote = 'exec-and-forget aerospace-scratchpad show Alacritty'
# cmd-alt-ctrl-g = 'exec-and-forget aerospace-scratchpad show ".+" --filter window-id=$(aerospace list-windows --focused --format '%{window-id}')'
cmd-alt-ctrl-quote = 'exec-and-forget aerospace-scratchpad show ".+" --filter window-id=$(cat /tmp/kjuq_aerospace_scratchpad_winid)'
# Hide current window: `aerospace-scratchpad show ".+" --filter window-id=$(aerospace list-windows --focused --format '%{window-id}')`

[exec.env-vars]
PATH = '/opt/homebrew/bin:${PATH}' # Scratchpad
# AEROSPACE_SCRATCHPAD_LOGS_LEVEL = "DEBUG"
