#!/bin/bash

mkdir --parents "$XDG_CACHE_HOME/X11"

# shellcheck disable=SC2034
USERXSESSION="$XDG_CACHE_HOME/X11/xsession"

# shellcheck disable=SC2034
USERXSESSIONRC="$XDG_CACHE_HOME/X11/xsessionrc"

# shellcheck disable=SC2034
ALTUSERXSESSION="$XDG_CACHE_HOME/X11/Xsession"

# shellcheck disable=SC2034
ERRFILE="$XDG_CACHE_HOME/X11/xsession-errors"

userresources="$XDG_CONFIG_HOME/X11/Xresources"

if [ -f "$userresources" ]; then
	xrdb -merge "$userresources"
fi

echo 'Xcursor.theme: Adwaita' | xrdb -merge

if [ "$(uname --nodename)" = "KOXPX" ]; then
	echo 'Xft.dpi: 168' | xrdb -merge
	echo 'Xcursor.size: 48' | xrdb -merge
fi

# Necessary!!
if [ -d /etc/X11/xinit/xinitrc.d ]; then
	for f in /etc/X11/xinit/xinitrc.d/?*.sh; do
		# shellcheck disable=SC1090
		[ -x "$f" ] && . "$f"
	done
	unset f
fi

if { command -v xrandr >/dev/null; } 2>&1; then
	xrandr --output eDP-1 --rotate left
fi

if { command -v xinput >/dev/null; } 2>&1; then
	xinput --map-to-output 'NVTK0603:00 0603:F001' eDP-1
fi

# if { command -v xset > /dev/null; } 2>&1 ; then
# 	xset dpms 900 1200 1500
# 	xset s noblank
# fi

if { command -v dunst >/dev/null; } 2>&1; then
	dunst &
fi

if { command -v keyboard_init >/dev/null; } 2>&1; then
	keyboard_init # ~/.local/kjuq_bin/keyboard_init
fi

exec i3
