#!/bin/bash

mkdir --parents "$XDG_CACHE_HOME/X11"

USERXSESSION="$XDG_CACHE_HOME/X11/xsession"
USERXSESSIONRC="$XDG_CACHE_HOME/X11/xsessionrc"
ALTUSERXSESSION="$XDG_CACHE_HOME/X11/Xsession"
ERRFILE="$XDG_CACHE_HOME/X11/xsession-errors"

userresources="$XDG_CONFIG_HOME/X11/Xresources"

if [ -f "$userresources" ]; then
	xrdb -merge "$userresources"
fi

# Device specific configurations

if [ "$(uname --nodename)" = "KOXPX" ]; then
	echo "Xft.dpi: 168" | xrdb -merge
fi

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
	for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
		[ -x "$f" ] && . "$f"
	done
	unset f
fi

xrandr --output eDP-1 --rotate left

copyq &

keyboard_init

exec i3
