quitOnTopLevelReturn: true # Quit with esc
promptToReturnFromSubprocess: false
gui:
  showIcons: true
git:
  disableForcePushing: true
keybinding:
  commits:
    viewResetOptions: D
  files:
    commitChanges: C
    commitChangesWithEditor: c
