#!/usr/bin/env bash

if [ "$(uname --nodename)" == "KOXPX" ]; then
	left="$(cat /sys/class/power_supply/BAT0/capacity)"
	ac="$(cat /sys/class/power_supply/BAT0/status)"
	if [ "$ac" = 'Charging' ]; then
		output="$left% $ac"
	else
		output="$left%"
	fi
	echo "$output"
fi
