#!/usr/bin/env bash

set -eu

if [ -z "${TERMUX_VERSION:-}" ]; then
	echo 'This environment is not Termux. Quit' 1>&2
	exit 1
fi

if ! command -v rsync &>/dev/null; then
	echo "Error: 'rsync' not found" 1>&2
	exit 1
fi

user="kjuq"
host="krp4b"
remote_home='./mount/buffalo_stick_ssd/storage'

local_path="$HOME/storage/dcim/"
remote_path='pictures/_android/dcim/'
rsync -av "$local_path" "$user@$host:$remote_home/$remote_path/"

local_path="$HOME/storage/pictures/"
remote_path='pictures/_android/pictures/'
rsync -av "$local_path" "$user@$host:$remote_home/$remote_path/"
