#!/usr/bin/env bash

query=""
while [ "$#" -gt 0 ]; do
	query="$query $1"
	shift
done

query=$(echo "$query" | sed 's/^[ \t]*//;s/[ \t]*$//')

if [ "$(uname)" = 'Linux' ]; then
	ggl_browser='xdg-open'
else
	ggl_browser='open'
fi

$ggl_browser "https://www.google.com/search?q=$query"
# $ggl_browser "https://duckduckgo.com/?q=$query"
# $ggl_browser "https://www.bing.com/search?q=$query"
# $ggl_browser "https://search.yahoo.co.jp/search?p=$query"
