#!/usr/bin/env bash

set -eu

if ! command -v curl &>/dev/null; then
	echo "Error: 'curl' not found"
	exit 1
fi

usage() {
	echo "Usage: $0 [-l] <image_path>"
	exit 1
}

# オプション解析用変数
use_local="false"

# オプション解析
while getopts "l" opt; do
	case "$opt" in
	l)
		use_local="true"
		;;
	*)
		usage
		;;
	esac
done
shift "$((OPTIND - 1))"

# 画像パスを引数から取得し、PATH にバインド (注意: PATH は環境変数と衝突するので本来は別名推奨)
if [ -z "$1" ]; then
	usage
fi
input="$1"

hostname='krp4b'
port=8000
username='kjuq'

# -l オプションが指定された場合は HOSTNAME に .local を付加
if [ "$use_local" = "true" ]; then
	hostname="${hostname}.local"
fi

extension="${input##*.}"
output="$(date +'%Y-%m-%d_%H-%M-%S_%N')_$(printf '%05d' $RANDOM).$extension"
output_dir='./mount/buffalo_stick_ssd/storage/assets/img'

scp -q "$input" "$username@$hostname:$output_dir/$output"

echo "http://$hostname:$port/img/$output"
