If:
  PathMatch: .*\.cpp
CompileFlags:
  Add:
    - -std=c++23
    - -I/home/linuxbrew/.linuxbrew/include/
    - -I/opt/homebrew/include/
---
CompileFlags:
  Add:
    - -Wall
    - -Wextra
    - -D_GLIBCXX_DEBUG
    - -D_LIBCPP_ENABLE_DEBUG_MODE
