vim.api.nvim_create_user_command("Sudowrite", "write !sudo tee % > /dev/null", {})
vim.api.nvim_create_user_command("ExMode", function()
	vim.api.nvim_feedkeys("gQ", "n", false)
end, {})
vim.api.nvim_create_user_command("SelectMode", function()
	vim.api.nvim_feedkeys("gh", "n", false)
end, {})
vim.api.nvim_create_user_command("SelectLineMode", function()
	vim.api.nvim_feedkeys("gH", "n", false)
end, {})
vim.api.nvim_create_user_command("VirtualReplace", function()
	vim.api.nvim_feedkeys("gr", "n", false)
end, {})
vim.api.nvim_create_user_command("VirtualReplaceMode", function()
	vim.api.nvim_feedkeys("gR", "n", false)
end, {})
vim.api.nvim_create_user_command("GQ", function()
	vim.api.nvim_feedkeys("gQ", "n", false)
end, {})
vim.api.nvim_create_user_command("Gh", function()
	vim.api.nvim_feedkeys("gh", "n", false)
end, {})
vim.api.nvim_create_user_command("GH", function()
	vim.api.nvim_feedkeys("gH", "n", false)
end, {})
vim.api.nvim_create_user_command("Gr", function()
	vim.api.nvim_feedkeys("gr", "n", false)
end, {})
vim.api.nvim_create_user_command("GR", function()
	vim.api.nvim_feedkeys("gR", "n", false)
end, {})
