local M = {}

M.snippets = {
	{
		trigger = 'image',
		body = {
			[[#figure(]],
			[[	image("${1:PATH}", width: 80%),]],
			[[	caption: []],
			[[		A caption. This is an example text.]],
			[[	],]],
			[[) <${2:LABEL}>]],
		},
	},
	{
		trigger = 'template',
		body = {
			[[#import "@preview/js:0.1.3": * // https://typst.app/universe/package/js/]],
			[[#show: js.with(]],
			[[	lang: "ja",]],
			[[	seriffont: "Libertinus Serif", // or "Libertinus Serif", ...]],
			[[	seriffont-cjk: "Noto Serif CJK JP", // or "Yu Mincho", "Hiragino Mincho ProN", ...]],
			[[	sansfont: "Hack Nerd Font", // or "Arial", "Helvetica", ...]],
			[[	sansfont-cjk: "Noto Sans CJK JP", // or "Yu Gothic", "Hiragino Kaku Gothic ProN", ...]],
			[[	paper: "a4", // "a*", "b*", or (paperwidth, paperheight) e.g. (210mm, 297mm)]],
			[[	fontsize: 12pt,]],
			[[	baselineskip: auto,]],
			[[	textwidth: auto,]],
			[[	lines-per-page: auto,]],
			[[	book: false, // or true]],
			[[	cols: 1, // 1, 2, 3, ...]],
			[[	non-cjk: regex("[\u0000-\u2023]"),  // or "latin-in-cjk" or any regex]],
			[[	cjkheight: 0.88, // height of CJK in em]],
			[[)]],
			[[]],
			[[#maketitle(]],
			[[	title: "Typst日本語用テンプレートjs",]],
			[[	// authors: "NAME",]],
			[[	// authors: ("NAME", "NAME"),]],
			[[	// authors: (("NAME", "UNIVERSITY"), ("NAME", "UNIVERSITY")),]],
			[[	authors: (("NAME", "UNIVERSITY", "mail@address.org"), ("NAME", "UNIVERSITY")),]],
			[[	// abstract: []],
			[[	// 	Typst template that imitates jsarticle/jsbook of #LaTeX]],
			[=[	// ]]=],
			[[)]],
		},
	},
	{
		trigger = 'titleFullpage',
		body = {
			[=[#show: rest => {]=],
			[=[	// 最初のページのみ特別なレイアウトを適用]=],
			[=[	align(center + horizon)[]=],
			[=[		#v(30%) // ページの上から30%の位置に配置]=],
			[=[		#text(22pt, weight: "bold")[TITLE]]=],
			[=[		#v(42%) // ページの中央より少し下に配置]=],
			[=[		NAME]=],
			[=[		#v(1fr) // 残りのスペースを埋める]=],
			[=[		#text(11pt)[2025-99-99]]=],
			[=[	]]=],
			[=[	pagebreak()]=],
			[=[	rest]=],
			[=[}]=],
		},
	},
	{
		trigger = 'setHeading',
		body = '#set heading(numbering: "1.1")',
	},
}

return M
